save_dir: "./cnn_ffc_weights"
load_path: ""
seed: 1
eps: 1.0e-6
use_amp: true
amp_dtype: "float16"
scaler_min_scale: -1.0
max_num_pts: 30000
dataset:
  mode: "train"
  coord_scale: 10.0
  type: "synthetic"
  white_bg: true
  factor: 1
  batch_size: 1
  shuffle: true
  extract_patch: true
  extract_online: true
  read_offline: false
  patches:
    height: 160
    width: 160
    max_patches: 10
geoms:
  points:
    load_path: ""
    select_k: 20
    select_k_type: "d2r"
    select_k_sorted: false
    init_type: "cube"
    init_scale: [1.2, 1.2, 1.2]
    init_center: [0.0, 0.0, 0.0]
    init_num: 10000
    influ_init_val: 0.0
    add_type: "random"
    add_k: 3
    add_sample_type: "top-knn-std"
    add_sample_k: 10
  background:
    learnable: false
    init_color: [1.0, 1.0, 1.0]
    constant: 5.0
  point_feats:
    dim: 64
    use_inv: true
    use_ink: false
    use_inq: false
  mapping_mlp:
    num_layers: 8
    dim: 256
    act: "relu"
    last_act: "relu+1"
    use_wn: false
    out_dim: 64
models:
  use_renderer: true
  last_act: "none"
  normalize_topk_attn: true
  attn:
    k_type: 1
    q_type: 1
    v_type: 1
    d_model: 256
    score_act: "relu"
    embed:
      embed_type: 1
      k_L: [6, 6, 6]
      q_L: [6]
      v_L: [6, 6]
      pe_factor: 2.0
      pe_mult_factor: 1.0
      key:
        d_ff: 256
        d_ff_out: 256
        n_ff_layer: 5
        ff_act: "relu"
        ff_act_a: 1.0
        ff_act_b: 1.0
        ff_act_trainable: false
        ff_last_act: "none"
        norm: "layernorm"
        dropout_ff: 0.0
        use_wn: false
        residual_ff: false
        skip_layers: []
        half_layers: []
        residual_layers: []
        residual_dims: []
      query:
        d_ff: 256
        d_ff_out: 256
        n_ff_layer: 5
        ff_act: "relu"
        ff_act_a: 1.0
        ff_act_b: 1.0
        ff_act_trainable: false
        ff_last_act: "none"
        norm: "layernorm"
        dropout_ff: 0.0
        use_wn: false
        residual_ff: false
        skip_layers: []
        half_layers: []
        residual_layers: []
        residual_dims: []
      value:
        d_ff: 256
        d_ff_out: 32
        n_ff_layer: 8
        ff_act: "relu"
        ff_act_a: 1.0
        ff_act_b: 1.0
        ff_act_trainable: false
        ff_last_act: "none"
        norm: "none"
        dropout_ff: 0.0
        use_wn: false
        residual_ff: false
        skip_layers: []
        half_layers: []
        residual_layers: []
        residual_dims: []
  renderer:
    generator:
      type: "unet"
      unet:
        bilinear: false
        norm: "none"
        single: true
        last_act: "none"
        affine_layer: -1
training:
  steps: 250000
  prune_steps: 500
  prune_start: 10000
  prune_stop: 150000
  prune_thresh: 0.0
  prune_thresh_list: []
  prune_steps_list: []
  prune_type: "<"
  add_steps: 1000
  add_start: 10000
  add_stop: 70000
  add_num: 1000
  add_num_list: []
  add_steps_list: []
  exclude_keys: []
  fix_keys: []
  losses:
    mse: 1.0
    lpips: 1.0e-2
    lpips_alex: 0.0
  lr:
    lr_factor: 1.0
    mapping_mlp:
      type: "none"
      base_lr: 1.0e-6
      factor: 1
      warmup: 0
      weight_decay: 0
    attn:
      type: "cosine-hlfperiod"
      base_lr: 3.0e-4
      factor: 1
      warmup: 10000
      weight_decay: 0
    points:
      type: "cosine"
      base_lr: 2.0e-3
      factor: 1
      warmup: 0
      weight_decay: 0
    bkg_feats:
      type: "none"
      base_lr: 0.0
      factor: 1
      warmup: 10000
      weight_decay: 0
    points_influ_scores:
      type: "cosine-hlfperiod"
      base_lr: 1.0e-3
      factor: 1
      warmup: 10000
      weight_decay: 0
    feats: 
      type: "cosine-hlfperiod"
      base_lr: 1.0e-3
      factor: 1
      warmup: 10000
      weight_decay: 0
    generator:
      type: "cosine-hlfperiod"
      base_lr: 1.0e-4
      factor: 1
      warmup: 10000
      weight_decay: 0
eval:
  dataset:
    name: "testset"
    mode: "test"
    extract_patch: false
    type: "synthetic"
    white_bg: true
    factor: 1
    num_workers: 0
    num_slices: -1
  step: 5000
  img_idx: 50
  max_height: 100
  max_width: 100
  save_fig: true
test:
  load_path: ""
  save_fig: true
  save_video: false
  max_height: 100
  max_width: 100
  datasets:
    - name: "testset"
      mode: "test"
      extract_patch: false
      type: "synthetic"
      white_bg: true
      factor: 1
      num_workers: 0
      num_slices: -1
  plots:
    pcrgb: true
    featattn: false